### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by ngsankar2** [ngsankar-lab/demo#1]
I think it looks better if the main title is bit more orange.

The styling rule could be changed like this:

``` css
h1{
color: #efa82e;
}
```
